### ISSUE TITLE
ADD SURVEY 

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/kaeffken#15]
```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	"github.com/charmbracelet/huh"
	"gopkg.in/yaml.v2"
)

// Question struct to hold the question data from YAML
type Question struct {
	Prompt          string   `yaml:"prompt"`
	Name            string   `yaml:"name"`
	Default         string   `yaml:"default,omitempty"`
	DefaultFunction string   `yaml:"default_function,omitempty"`
	Options         []string `yaml:"options"`
	Kind            string   `yaml:"kind,omitempty"`
	MinLength       int      `yaml:"minLength,omitempty"`
	MaxLength       int      `yaml:"maxLength,omitempty"`
}

// Function mapping
var defaultFunctions = map[string]func() string{
	"getDefaultFavoriteFood": func() string { return "steak" },
	"getDefaultDrink":        func() string { return "water" },
}

// Load questions from YAML file
func loadQuestions(filename string) ([]*Question, error) {
	var questions []*Question
	data, err := ioutil.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	err = yaml.Unmarshal(data, &questions)
	if err != nil {
		return nil, err
	}

	return questions, nil
}

// Build the survey form from the loaded questions
func buildSurvey(questions []*Question) (*huh.Form, error) {
	var groupFields []*huh.Group

	// Iterate over each question to create the survey fields
	for _, question := range questions {
		// Resolve default value
		if question.DefaultFunction != "" {
			if fn, ok := defaultFunctions[question.DefaultFunction]; ok {
				question.Default = fn()
			} else {
				return nil, fmt.Errorf("default function %s not found", question.DefaultFunction)
			}
		}

		var field huh.Field

		switch question.Kind {
		case "text":
			// Handle text input with validation
			field = huh.NewInput().
				Title(question.Prompt).
				Value(&question.Default).
				Validate(func(input string) error {
					if len(input) < question.MinLength {
						return fmt.Errorf("input too short, minimum length is %d", question.MinLength)
					}
					if len(input) > question.MaxLength {
						return fmt.Errorf("input too long, maximum length is %d", question.MaxLength)
					}
					return nil
				})

		default:
			// Handle multiple choice select options
			options := make([]huh.Option[string], len(question.Options))
			for i, opt := range question.Options {
				options[i] = huh.NewOption(opt, opt)
			}

			field = huh.NewSelect[string]().
				Title(question.Prompt).
				Options(options...).
				Value(&question.Default)
		}

		// Create a group and add the field to it
		group := huh.NewGroup(field)
		groupFields = append(groupFields, group)
	}

	// Create and return the form
	return huh.NewForm(groupFields...), nil
}

func main() {
	// Load the questions from the YAML file
	questions, err := loadQuestions("survey.yaml")
	if err != nil {
		log.Fatalf("Error loading questions: %v", err)
	}

	// Build the survey form
	form, err := buildSurvey(questions)
	if err != nil {
		log.Fatalf("Error building survey: %v", err)
	}

	// Run the survey form
	err = form.Run()
	if err != nil {
		log.Fatalf("Error running survey: %v", err)
	}

	// Output the answers
	fmt.Println("\nYour answers:")
	for _, question := range questions {
		fmt.Printf("%s: %s\n", question.Name, question.Default)
	}
}
```

```yaml
- prompt: "Do you like Go?"
  name: go
  default: "Yes"
  options:
    - "Yes"
    - "No"

- prompt: "Do you have any pets?"
  name: pets
  default: "Yes"
  options:
    - "Yes"
    - "No"

- prompt: "What is your favorite color?"
  name: color
  default: "Blue"
  options:
    - "Red"
    - "Blue"
    - "Green"
    - "Yellow"

- prompt: "What is your favorite food?"
  name: food
  kind: text
  default_function: getDefaultFavoriteFood
  minLength: 3
  maxLength: 20
```
